language: java

deploy:
  provider: pages
  skip_cleanup: true

  env:
    global:
      - github_token=0b3b6259dd92b0177b344f64f23b163a4307d948
  #Authorization: token <0b3b6259dd92b0177b344f64f23b163a4307d948>
  github_token: github_token  # Set in the settings page of your repository, as a secure variable
  #repo: 0b3b6259dd92b0177b344f64f23b163a4307d948
  keep_history: true
  on:
    branch: master